Getting the setup script to work on Intel based Mac machines
exo-explore/exo pull request #373
Opened 2024-10-22 06:46 UTC by willschneider15

When trying to run the setup script on an Intel-based Mac I ran into the following issue installing MLX:

<img width="1016" alt="Screenshot 2024-10-22 at 1 54 33 AM" src="https://github.com/user-attachments/assets/0fc4601e-26f5-4d67-b49b-666893a26d40">

To fix the issue I updated the logic to check that they are using Arm64 in addition to Darwin before installing the MLX packages.

2024-10-22 17:03 UTC, AlexCheema requested changes

2024-10-22 17:03 UTC, AlexCheema commented on install.sh
Is it possible to put this logic in `setup.py` since it's not required to use `install.sh`

2024-10-22 18:06 UTC, willschneider15 commented on install.sh
Yep I just pushed the update

2024-10-22 18:09 UTC, willschneider15 commented on install.sh
Tested on my Intel Mac.

If possible, it would be a good idea to test the setup on an M series (Apple Silicon) chip before merging, to ensure that MLX installs correctly.

2024-10-23 07:01 UTC, AlexCheema commented
Awesome. LGTM!

2024-10-23 07:02 UTC, merged