Some initial inference engine refactors for enabling training
exo-explore/exo pull request #420
Opened 2024-11-09 09:22 UTC by blindcrone

Only on MLX for now, breaks Tinygrad (doesn't fulfill interface yet)

2024-11-10 00:20 UTC, dtnewman commented on exo/inference/inference_engine.py
> +  async def sample(self, x: np.ndarray) -> np.ndarray:
Should this be an abstract method?

2024-11-10 08:18 UTC, blindcrone commented on exo/inference/inference_engine.py
> +  async def sample(self, x: np.ndarray) -> np.ndarray:
O yup, sure should

2024-11-11 09:12 UTC, blindcrone commented
Okay this no longer breaks tinygrad afaict

2024-11-11 15:11 UTC, AlexCheema requested changes
This looks great. Just take a Quick Look through my comments - there's 1 or 2 actionable things.

2024-11-11 15:11 UTC, AlexCheema commented on exo/inference/mlx/sharded_model.py
> +      self.caches.move_to_end(request_id)
nice so it's an LRU cache

2024-11-11 15:11 UTC, AlexCheema commented on exo/inference/tinygrad/inference.py
> +      return sample_logits(Tensor(logits).flatten(), TEMPERATURE, 0, 0.8, 0.0, 0.0).realize()
not necessary in this PR but I think now that we have sampling happening at this level, we could make TEMPERATURE, TOP_K and whatever other parameters for sampling something that's configurable. This is actually part of the ChatGPT-API-Spec: you can pass temperature, but right now it doesn't do anything lol

2024-11-11 15:11 UTC, AlexCheema commented on exo/inference/tinygrad/models/llama.py
> +    self.caches = OrderedDict()
Is this a hack? I didn't think the caches would be in the model implementation itself?

2024-11-11 15:11 UTC, AlexCheema commented on exo/orchestration/standard_node.py
> +  def get_partition_index(self, offset: int = 0):
offset is a future thing you're thinking about?

2024-11-12 11:31 UTC, AlexCheema commented
beast mode.

2024-11-12 11:32 UTC, merged