feat: Implement cross-platform executable compilation and distribution (WIP)
exo-explore/exo pull request #451
Opened 2024-11-13 10:46 UTC by SethBurkart123

This work-in-progress pull request aims to transform exo into an easily installable executable for multiple platforms, streamlining the distribution process. Previous issue #334 was incorrectly closed by Github automatically.

Objectives:
- [x] Create a comprehensive PyInstaller spec file to bundle all required dependencies
- [x] Implement CI/CD workflows for automated executable builds
- [x] Ensure mac builds work
- [ ] Ensure linux builds work
- [ ] Ensure windows builds work
- [ ] Conduct comprehensive cross-platform testing to ensure complete functionality
- [ ] Package the executable in an installation-ready format
- [x] Develop scripts for submission to Homebrew

Key improvements:
1. Simplified installation process for end-users
2. Broader platform compatibility
3. Automated build and distribution pipeline

Related #302

2024-11-13 14:47 UTC, dtnewman commented on build.sh
> +#rm -rf build dist
this should be uncommented

2024-11-13 14:48 UTC, dtnewman commented on build.sh
> +#pyinstaller exo.spec
where is the exo.spec file?

2024-11-13 14:50 UTC, dtnewman commented
interesting approach! Just FYI, this is being worked on in https://github.com/exo-explore/exo/pull/354. As far as I can tell (from looking at the package you generated in your releases on GitHub), this creates an executable along with a directory of supporting libraries needed to run it. PR 354 allows for a single file to be generated.

2024-11-13 17:04 UTC, lgcyaxi requested changes
Don't submit the .DS_Store file. Please add it to .gitignore

2024-11-13 19:09 UTC, SethBurkart123 commented
> interesting approach! Just FYI, this is being worked on in #354. As far as I can tell (from looking at the package you generated in your releases on GitHub), this creates an executable along with a directory of supporting libraries needed to run it. PR 354 allows for a single file to be generated.

I'm currently developing all of those changes locally, the disadvantage with generating a single file executable is quite large cold start times. It's definitely an option I have played with but on each execution all libraries need to be unpacked for it to run causing it to take a while to load up.

2024-11-15 11:45 UTC, blindcrone commented
I can probably contribute at least an aur package to this lol

2024-11-15 11:47 UTC, blindcrone commented
Might be worth making it a bit more client-servery though, I would like for this to be able to sanely run under systemd at least

2025-12-18 14:10 UTC, Evanev7 commented
Thanks so much for your contribution and for taking the time to open this PR.

Since this repository has been fully rewritten and the license has changed, I’m closing all existing open PRs to avoid confusion and to align with the new codebase.

I really appreciate your interest in the project, and you’re very welcome to open a new PR against the updated version if you’d like and we look forward to reviewing it!

2025-12-18 14:10 UTC, closed without merging