package exo as installable
exo-explore/exo pull request #470
Opened 2024-11-18 16:56 UTC by josh1593

#302

2024-11-19 01:56 UTC, dtnewman commented on exo/main.py
> +import subprocess
I don't think `subprocess` gets used

2024-11-19 01:58 UTC, dtnewman commented on exo/api/chatgpt_api.py
> +    from exo.main import shutdown
now that `shutdown` is used in multiple places, I (personally) think it'd be more intuitive for it to live in helpers.py

2024-11-19 09:19 UTC, AlexCheema requested changes

2024-11-19 09:19 UTC, AlexCheema commented on exo/main.py
> +    await move_models_to_hf()
Pass in `args.model_seed_dir`

2024-11-19 09:19 UTC, AlexCheema commented on exo/download/hf/hf_helpers.py
> +async def move_models_to_hf():
Needs to take an argument

2024-11-19 09:43 UTC, AlexCheema requested changes

2024-11-19 09:43 UTC, AlexCheema commented on exo/download/hf/hf_helpers.py
> +      shutil.move(str(path), str(dest_path))
any way to make this async?

2024-11-19 09:43 UTC, AlexCheema commented on exo/main.py
> +      await move_models_to_hf(seed_dir)
no need for special case.

2024-11-19 12:55 UTC, AlexCheema commented
LGTM

2024-11-19 12:55 UTC, merged

2024-11-21 06:06 UTC, OKHand-Zy commented
> this is addressed on pr #473

Hi, I'd like to know if the change made on line 186 of exo/inference/mlx/sharded_utils.py is crucial.
```Python
tokenizer = load_tokenizer(model_path, tokenizer_config) => tokenizer = await resolve_tokenizer(model_path)
```
When I try to support local models, I encounter an issue, but it's resolved after reverting the change. So I'm wondering if this change is really necessary. If it's not that important, I'd prefer to use the old method.

2024-11-21 13:40 UTC, OKHand-Zy commented
> This change is correct. We should keep using `resolve_tokenizer` as it's async. We should not have sync blocking I/O code.
> 
> @OKHand-Zy you will need to fix your code to work with `resolve_tokenizer`

Okay, I'll try to modify my code to make `resolve_tokenizer` work properly.