Stable diffusion mlx
exo-explore/exo pull request #474
Opened 2024-11-20 04:32 UTC by pranav4501

Sharded stable diffusion inference for mlx

Changes:
- Sharded Stable Diffusion 2-1 Base mlx
- Handled diffusion steps by looping the whole model 
- Added back inference state 
- Modified grpc and proto to support inference 
- New endpoint for image generation
- Streaming progress for image generation

2024-11-21 14:19 UTC, pranav4501 commented
There are no changes to that part. It's how the partition algorithm splits the shards across the devices.

2024-11-22 06:54 UTC, AlexCheema commented
> There are no changes to that part. It's how the partition algorithm splits the shards across the devices.

I see. The difference here is the layers are non-uniform. That means they won't necessarily get split proportional to the memory used right?

2024-11-22 15:16 UTC, pranav4501 commented
Yeah, layers are non-uniform, so the split memory isn't exactly proportional to the number of layers. Can we split using the number of params?

2024-11-22 15:23 UTC, AlexCheema commented
> Yeah, layers are non-uniform, so the split memory isn't exactly proportional to the number of layers. Can we split using the number of params?

This is probably fine as long as the layers aren't wildly different in size. Do you know roughly how different in size they are?

2024-11-22 20:38 UTC, pranav4501 commented
Unet does have couple larger layers because of upsampled dims and clip text encoder has comparatively smaller layers as it can be easily split similar to llms, made of transformer blocks. We can combine 2 clip layers and split UNET further to make it more uniform. 
CLIP ( 1.36GB -> 22 layers : uniformly split), UNET ( 3.46GB -> 10 layers: non-uniform), VAE (346 MB -> 10 layers : non-uniform )

2024-11-23 04:06 UTC, blindcrone commented
I think at some point it would make sense to allow more granular sharding of models than just transformer blocks anyway, and this could involve updating to a memory-footprint heuristic based on dtypes and parameters rather than assuming uniform layer blocks

2024-11-25 08:51 UTC, AlexCheema commented
Was running on this branch for a while doing image generation requests and got the following errors:

```


model: stable-diffusion-2-1-base, prompt: A lion in a jungle, stream: False
shard: Shard(model_id='stable-diffusion-2-1-base', start_layer=0, end_layer=0, n_layers=37)
  2%|#9                                                                                               | 1/50 [00:00<?, ?it/s]
  2%|#9                                                                                               | 1/50 [00:00<?, ?it/s]

  4%|###8                                                                                             | 2/50 [00:00<?, ?it/s]
  4%|###8                                                                                             | 2/50 [00:00<?, ?it/s]

  6%|#####8                                                                                           | 3/50 [00:00<?, ?it/s]
  6%|#####8                                                                                           | 3/50 [00:00<?, ?it/s]

  8%|#######7                                                                                         | 4/50 [00:00<?, ?it/s]
  8%|#######7                                                                                         | 4/50 [00:00<?, ?it/s]

 10%|#########7                                                                                       | 5/50 [00:00<?, ?it/s]
 10%|#########7                                                                                       | 5/50 [00:00<?, ?it/s]

 12%|###########6                                                                                     | 6/50 [00:00<?, ?it/s]
 12%|###########6                                                                                     | 6/50 [00:00<?, ?it/s]

 14%|#############5                                                                                   | 7/50 [00:00<?, ?it/s]
 14%|#############5                                                                                   | 7/50 [00:00<?, ?it/s]

 16%|###############5                                                                                 | 8/50 [00:00<?, ?it/s]
 16%|###############5                                                                                 | 8/50 [00:00<?, ?it/s]

 18%|#################4                                                                               | 9/50 [00:00<?, ?it/s]
 18%|#################4                                                                               | 9/50 [00:00<?, ?it/s]

 20%|###################2                                                                            | 10/50 [00:00<?, ?it/s]
 20%|###################2                                                                            | 10/50 [00:00<?, ?it/s]

 22%|#####################1                                                                          | 11/50 [00:00<?, ?it/s]
 22%|#####################1                                                                          | 11/50 [00:00<?, ?it/s]

 24%|#######################                                                                         | 12/50 [00:00<?, ?it/s]
 24%|#######################                                                                         | 12/50 [00:00<?, ?it/s]

 26%|########################9                                                                       | 13/50 [00:00<?, ?it/s]
 26%|########################9                                                                       | 13/50 [00:00<?, ?it/s]

 28%|##########################8                                                                     | 14/50 [00:00<?, ?it/s]
 28%|##########################8                                                                     | 14/50 [00:00<?, ?it/s]

 30%|############################8                                                                   | 15/50 [00:00<?, ?it/s]
 30%|############################8                                                                   | 15/50 [00:00<?, ?it/s]

 32%|##############################7                                                                 | 16/50 [00:00<?, ?it/s]
 32%|##############################7                                                                 | 16/50 [00:00<?, ?it/s]

 34%|################################6                                                               | 17/50 [00:00<?, ?it/s]
 34%|################################6                                                               | 17/50 [00:00<?, ?it/s]

 36%|##################################5                                                             | 18/50 [00:00<?, ?it/s]
 36%|##################################5                                                             | 18/50 [00:00<?, ?it/s]

 38%|####################################4                                                           | 19/50 [00:00<?, ?it/s]
 38%|####################################4                                                           | 19/50 [00:00<?, ?it/s]

 40%|######################################4                                                         | 20/50 [00:00<?, ?it/s]
 40%|######################################4                                                         | 20/50 [00:00<?, ?it/s]

 42%|########################################3                                                       | 21/50 [00:00<?, ?it/s]
 42%|########################################3                                                       | 21/50 [00:00<?, ?it/s]

 44%|##########################################2                                                     | 22/50 [00:00<?, ?it/s]
 44%|##########################################2                                                     | 22/50 [00:00<?, ?it/s]

 46%|############################################1                                                   | 23/50 [00:00<?, ?it/s]
 46%|############################################1                                                   | 23/50 [00:00<?, ?it/s]

 48%|##############################################                                                  | 24/50 [00:00<?, ?it/s]
 48%|##############################################                                                  | 24/50 [00:00<?, ?it/s]

 50%|################################################                                                | 25/50 [00:00<?, ?it/s]
 50%|################################################                                                | 25/50 [00:00<?, ?it/s]

 52%|#################################################9                                              | 26/50 [00:00<?, ?it/s]
 52%|#################################################9                                              | 26/50 [00:00<?, ?it/s]

 54%|###################################################8                                            | 27/50 [00:00<?, ?it/s]
 54%|###################################################8                                            | 27/50 [00:00<?, ?it/s]

 56%|#####################################################7                                          | 28/50 [00:00<?, ?it/s]
 56%|#####################################################7                                          | 28/50 [00:00<?, ?it/s]

 58%|#######################################################6                                        | 29/50 [00:00<?, ?it/s]
 58%|#######################################################6                                        | 29/50 [00:00<?, ?it/s]

 60%|#########################################################6                                      | 30/50 [00:00<?, ?it/s]
 60%|#########################################################6                                      | 30/50 [00:00<?, ?it/s]

 62%|###########################################################5                                    | 31/50 [00:00<?, ?it/s]
 62%|### [...]

2024-11-25 09:18 UTC, AlexCheema commented
> Was running on this branch for a while doing image generation requests and got the following errors:
> 
> ```
> 
> 
> model: stable-diffusion-2-1-base, prompt: A lion in a jungle, stream: False
> shard: Shard(model_id='stable-diffusion-2-1-base', start_layer=0, end_layer=0, n_layers=37)
>   2%|#9                                                                                               | 1/50 [00:00<?, ?it/s]
>   2%|#9                                                                                               | 1/50 [00:00<?, ?it/s]
> 
>   4%|###8                                                                                             | 2/50 [00:00<?, ?it/s]
>   4%|###8                                                                                             | 2/50 [00:00<?, ?it/s]
> 
>   6%|#####8                                                                                           | 3/50 [00:00<?, ?it/s]
>   6%|#####8                                                                                           | 3/50 [00:00<?, ?it/s]
> 
>   8%|#######7                                                                                         | 4/50 [00:00<?, ?it/s]
>   8%|#######7                                                                                         | 4/50 [00:00<?, ?it/s]
> 
>  10%|#########7                                                                                       | 5/50 [00:00<?, ?it/s]
>  10%|#########7                                                                                       | 5/50 [00:00<?, ?it/s]
> 
>  12%|###########6                                                                                     | 6/50 [00:00<?, ?it/s]
>  12%|###########6                                                                                     | 6/50 [00:00<?, ?it/s]
> 
>  14%|#############5                                                                                   | 7/50 [00:00<?, ?it/s]
>  14%|#############5                                                                                   | 7/50 [00:00<?, ?it/s]
> 
>  16%|###############5                                                                                 | 8/50 [00:00<?, ?it/s]
>  16%|###############5                                                                                 | 8/50 [00:00<?, ?it/s]
> 
>  18%|#################4                                                                               | 9/50 [00:00<?, ?it/s]
>  18%|#################4                                                                               | 9/50 [00:00<?, ?it/s]
> 
>  20%|###################2                                                                            | 10/50 [00:00<?, ?it/s]
>  20%|###################2                                                                            | 10/50 [00:00<?, ?it/s]
> 
>  22%|#####################1                                                                          | 11/50 [00:00<?, ?it/s]
>  22%|#####################1                                                                          | 11/50 [00:00<?, ?it/s]
> 
>  24%|#######################                                                                         | 12/50 [00:00<?, ?it/s]
>  24%|#######################                                                                         | 12/50 [00:00<?, ?it/s]
> 
>  26%|########################9                                                                       | 13/50 [00:00<?, ?it/s]
>  26%|########################9                                                                       | 13/50 [00:00<?, ?it/s]
> 
>  28%|##########################8                                                                     | 14/50 [00:00<?, ?it/s]
>  28%|##########################8                                                                     | 14/50 [00:00<?, ?it/s]
> 
>  30%|############################8                                                                   | 15/50 [00:00<?, ?it/s]
>  30%|############################8                                                                   | 15/50 [00:00<?, ?it/s]
> 
>  32%|##############################7                                                                 | 16/50 [00:00<?, ?it/s]
>  32%|##############################7                                                                 | 16/50 [00:00<?, ?it/s]
> 
>  34%|################################6                                                               | 17/50 [00:00<?, ?it/s]
>  34%|################################6                                                               | 17/50 [00:00<?, ?it/s]
> 
>  36%|##################################5                                                             | 18/50 [00:00<?, ?it/s]
>  36%|##################################5                                                             | 18/50 [00:00<?, ?it/s]
> 
>  38%|####################################4                                                           | 19/50 [00:00<?, ?it/s]
>  38%|####################################4                                                           | 19/50 [00:00<?, ?it/s]
> 
>  40%|######################################4                                                         | 20/50 [00:00<?, ?it/s]
>  40%|######################################4                                                         | 20/50 [00:00<?, ?it/s]
> 
>  42%|########################################3                                                       | 21/50 [00:00<?, ?it/s]
>  42%|########################################3                                                       | 21/50 [00:00<?, ?it/s]
> 
>  44%|##########################################2                                                     | 22/50 [00:00<?, ?it/s]
>  44%|##########################################2                                                     | 22/50 [00:00<?, ?it/s]
> 
>  46%|############################################1                                                   | 23/50 [00:00<?, ?it/s]
>  46%|############################################1                                                   | 23/50 [00:00<?, ?it/s]
> 
>  48%|##############################################                                                  | 24/50 [00:00<?, ?it/s]
>  48%|##############################################                                                  | 24/50 [00:00<?, ?it/s]
> 
>  50%|################################################                                                | 25/50 [00:00<?, ?it/s]
>  50%|################################################                                                | 25/50 [00:00<?, ?it/s]
> 
>  52%|#################################################9                                              | 26/50 [00:00<?, ?it/s]
>  52%|#################################################9                                              | 26/50 [00:00<?, ?it/s]
> 
>  54%|###################################################8                                            | 27/50 [00:00<?, ?it/s]
>  54%|###################################################8                                            | 27/50 [00:00<?, ?it/s]
> 
>  56%|#####################################################7                                          | 28/50 [00:00<?, ?it/s]
>  56%|#####################################################7                                          | 28/50 [00:00<?, ?it/s]
> 
>  58%|#######################################################6                                        | 29/50 [00:00<?, ?it/s]
>  58%|#######################################################6                                        | 29/50 [00:00<?, ?it/s]
> 
>  60%|#########################################################6                                      | 30/50 [00:00<?, ?it/s]
>  60%|#########################################################6       [...]

2024-11-25 22:51 UTC, pranav4501 commented
Resolved!

2024-11-26 06:23 UTC, AlexCheema commented
Can we also support chat history? I want to be able to give follow-up instructions like:

Me: Generate an image of a robot in a flower field
> Generates image
Me: Make the flowers purple
> Should generate a modified image with purple flowers

2024-11-26 06:26 UTC, AlexCheema commented
Also, we need to persist the images in a system-wide location rather than in the exo repo itself.

2024-11-26 15:35 UTC, pranav4501 commented
For chat history, we can implement it as follows:
- select a previous image from chat history or upload an image
- then perform image-to-image generation using the image and the prompt
I can change the location of the images, Shall I move it to Documents/Exo?

2024-12-05 03:58 UTC, pranav4501 commented
Hi Alex, 
It now supports chat history
1. You can select the previously generated image from chat history by clicking on it
2. Then add an additional prompt to perform further image-to-image generation.
3. The caveat here is that the image-to-image generation requires an additional image encoder relative to text-to-image generation.
4. Also moved the images location to Documents/Exo/Images/

2024-12-13 21:36 UTC, AlexCheema commented
> Hi Alex, It now supports chat history
> 
> 1. You can select the previously generated image from chat history by clicking on it
> 2. Then add an additional prompt to perform further image-to-image generation.
> 3. The caveat here is that the image-to-image generation requires an additional image encoder relative to text-to-image generation.
> 4. Also moved the images location to Documents/Exo/Images/

The follow-up prompts aren't working for me. I selected an image of flowers and added "with a horse galloping through" and it seems to ignore the selected image.

<img width="1361" alt="Screenshot 2024-12-13 at 21 36 05" src="https://github.com/user-attachments/assets/be4caebe-56c8-4a40-88c4-687675c76706" />

2024-12-16 23:53 UTC, pranav4501 commented
I don't think it is ignoring the previous image here, but it creates a latent using the encoded image and encoded prompt to generate a new image. So, it is not editing the previous image. We can set the strength of the prompt in the newly generated image. For a smaller strength, many features of the older images are carried over but the features of the prompt are not fully generated. 
You can try generating with smaller strengths by updating it here
https://github.com/pranav4501/exo/blob/5c0cd1839bdddd549a0a3f51e97064f7cc58ff8e/exo/inference/mlx/models/StableDiffusionPipeline.py#L184

2024-12-23 23:52 UTC, AlexCheema requested changes
There are some architectural improvements I'd like to make here. Some high level notes:
- `inference_state` shouldn't be necessary
- Special cases for stable diffusion
- Cache handling can be unified / made more flexible with e.g. prompt caching / preloading the cache with a serialized cache
- Tokenizer handling is hacky and should be unified - you had to write a new tokenizer for example

For now I think this is good to merge if you fix the things I made comments on and we will work on these architectural changes later.

2024-12-23 23:52 UTC, AlexCheema commented on build/lib/exo/__init__.py
Why is there a bulld dir?

2024-12-23 23:52 UTC, AlexCheema commented on exo/inference/mlx/sharded_utils.py
> +  models_config = json.loads(models_config)
is this to sanitize the json?

2024-12-31 00:08 UTC, pranav4501 commented on build/lib/exo/__init__.py
Missed that!

2024-12-31 00:08 UTC, pranav4501 commented on exo/inference/mlx/sharded_utils.py
> +  models_config = json.loads(models_config)
I think it should work without it

2024-12-31 00:22 UTC, pranav4501 commented
Merged latest and resolved latest changes. I will try to refine it more.
Regarding special cases, 
- I will try to remove the hardcoding from model loading
- I think we have to classify models by architecture and handle them as required or hide the architecture specific part from networking, for e.g, sampling in node.py 
Regarding Inference state
- Unet requires many previous states
- The diffusion model requires the current step preserved
Maybe we can mask them into input

2025-01-12 02:57 UTC, AlexCheema approved these changes
lets get this merged.

2025-01-12 02:57 UTC, merged